customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: |
      aichat -m deepseek "Пожалуйста, напишите commit message для следующего коммита, используя результат команды git diff:

        \`\`\`diff
        $(git diff --staged)
        \`\`\`

        **Пример сообщения коммита:**

        Краткое описание изменений.

          added:
            - какие сущности, методы, классы или логика добавлены и т.д.
          removed:
            - какие сущности, методы, классы или логика удалены и т.д.
          modified:
            - какие сущности, методы, классы или логика изменены и т.д.
          moved:
            - какие сущности, методы, классы или логика перемещены и т.д.

        **Выходной шаблон**
        Обязательно используй этот шаблон, вывод которого ниже. Не используй переносы строк, лишние пробелы, лишние символы. Не украшай текст.

        \`\`\`
        $(cat .git/.template)
        \`\`\`


        **Используй предыдущие коммиты для примера:**

        \`\`\`
        $(git log -n 5 --pretty=format:'%h %s')
        \`\`\`

        Напиши свой commit message строго соблюдая шаблон. Пиши на английском. В шаблоне обязательно должны быть заполнены все секции. 
        Не углубляйся в детали, описывай только суть того, что поменялось или добавилось."\
          | fzf --height 40% --border --ansi --read0 --preview "echo {}" --preview-window=up:wrap \
          | xargs -0 -J {} bash -c '
              COMMIT_MSG_FILE=$(mktemp)
              printf "%s" "$1" > "$COMMIT_MSG_FILE"
              ${EDITOR:-nvim} "$COMMIT_MSG_FILE"
              if [ -s "$COMMIT_MSG_FILE" ]; then
                git commit -F "$COMMIT_MSG_FILE"
              else
                echo "Commit message was not saved, commit aborted."
              fi
              rm -f "$COMMIT_MSG_FILE"' _ {}
    context: files
    output: terminal
